In [1]:
import pandas as pd

In [2]:
# Reading an Excel Sheet

In [3]:
df = pd.read_csv('Employee.csv')

In [4]:
# Exploring Dataframe Attributes

In [5]:
print(df.shape)
print(df.columns)
# print(countries.info)

(5, 4)
Index(['EmployeeID', 'Name', 'Country', 'Salary'], dtype='object')

In [6]:
# Select/Filter specific columns from the dataset

In [7]:
selected_columns = df[['Country', 'Salary']]
selected_columns

       Country   Salary
0  Afghanistan  50000.0
1      Albania      NaN
2  Afghanistan  55000.0
3      Algeria  70000.0
4  Afghanistan  45000.0

In [8]:
afghanistan_df = df[df['Country'] == 'Afghanistan']
afghanistan_df

   EmployeeID         Name      Country   Salary
0           1     John Doe  Afghanistan  50000.0
2           3     Ali Khan  Afghanistan  55000.0
4           5  David Brown  Afghanistan  45000.0

In [9]:
Modified_employee_id_df = df[df['EmployeeID']!= 3]
Modified_employee_id_df

   EmployeeID         Name      Country   Salary
0           1     John Doe  Afghanistan  50000.0
1           2    Ane Smith      Albania      NaN
3           4     Sara Ali      Algeria  70000.0
4           5  David Brown  Afghanistan  45000.0

In [10]:
# Filtering rows based on a condition
filtered_df = df[df['Salary'] > 5000]
filtered_df

   EmployeeID         Name      Country   Salary
0           1     John Doe  Afghanistan  50000.0
2           3     Ali Khan  Afghanistan  55000.0
3           4     Sara Ali      Algeria  70000.0
4           5  David Brown  Afghanistan  45000.0

In [11]:
# Sorting
sorted_df = df.sort_values(by='EmployeeID', ascending=True)
sorted_df

   EmployeeID         Name      Country   Salary
0           1     John Doe  Afghanistan  50000.0
1           2    Ane Smith      Albania      NaN
2           3     Ali Khan  Afghanistan  55000.0
3           4     Sara Ali      Algeria  70000.0
4           5  David Brown  Afghanistan  45000.0

In [12]:
# Aggregation
aggregated_df = df.groupby('Salary').sum()
new_aggregated_df = pd.DataFrame(aggregated_df)

new_aggregated_df

         EmployeeID         Name      Country
Salary
45000.0           5  David Brown  Afghanistan
50000.0           1     John Doe  Afghanistan
55000.0           3     Ali Khan  Afghanistan
70000.0           4     Sara Ali      Algeria

In [13]:
# Merging DataFrames: Concat, Merge Functions

# Sample DataFrame 1
df1 = df[['EmployeeID', 'Name', 'Country']]

# Sample DataFrame 2
df2 = df[['EmployeeID', 'Salary']]

# Concat
concat_df = pd.concat([df1, df2], axis=1)

# Merge
merged_by_left_join_df = pd.merge(df1, df2, on='EmployeeID', how = 'left')
merged_by_right_join_df = pd.merge(df1, Modified_employee_id_df, on='EmployeeID', how = 'right') # inner, outer


print(concat_df.head())

   EmployeeID         Name      Country  EmployeeID   Salary
0           1     John Doe  Afghanistan           1  50000.0
1           2    Ane Smith      Albania           2      NaN
2           3     Ali Khan  Afghanistan           3  55000.0
3           4     Sara Ali      Algeria           4  70000.0
4           5  David Brown  Afghanistan           5  45000.0

In [14]:
print(merged_by_left_join_df.head())

   EmployeeID         Name      Country   Salary
0           1     John Doe  Afghanistan  50000.0
1           2    Ane Smith      Albania      NaN
2           3     Ali Khan  Afghanistan  55000.0
3           4     Sara Ali      Algeria  70000.0
4           5  David Brown  Afghanistan  45000.0

In [15]:
print(merged_by_right_join_df.head())

   EmployeeID       Name_x    Country_x       Name_y    Country_y   Salary
0           1     John Doe  Afghanistan     John Doe  Afghanistan  50000.0
1           2    Ane Smith      Albania    Ane Smith      Albania      NaN
2           4     Sara Ali      Algeria     Sara Ali      Algeria  70000.0
3           5  David Brown  Afghanistan  David Brown  Afghanistan  45000.0

In [16]:
# Handling Missing Data: Identify Missing Values, Fill Missing Values, Drop Missing Values

# Identifying missing values
missing_values = df.isnull().sum()

# Fill missing values
df_filled = df.fillna(0)

# Drop missing values
df_dropped = df.dropna()

print('Missing Values:')
print(missing_values)
print('DataFrame with Filled Missing Values:')
print(df_filled.head())
print('DataFrame with Dropped Missing Values:')
print(df_dropped.head())

Missing Values:
EmployeeID    0
Name          0
Country       0
Salary        1
dtype: int64
DataFrame with Filled Missing Values:
   EmployeeID         Name      Country   Salary
0           1     John Doe  Afghanistan  50000.0
1           2    Ane Smith      Albania      0.0
2           3     Ali Khan  Afghanistan  55000.0
3           4     Sara Ali      Algeria  70000.0
4           5  David Brown  Afghanistan  45000.0
DataFrame with Dropped Missing Values:
   EmployeeID         Name      Country   Salary
0           1     John Doe  Afghanistan  50000.0
2           3     Ali Khan  Afghanistan  55000.0
3           4     Sara Ali      Algeria  70000.0
4           5  David Brown  Afghanistan  45000.0

In [17]:
# Exporting DataFrame to Excel ".CSV"

df_dropped.to_csv('Employee_output.csv', index=False)